/*
 * frmNearestPOI.java
 *
 * Created on January 16, 2008, 5:29 AM
 */

package RouteSearch;

import GuideME.Main;
import GuideME.StringEX;

/**
 *
 * @author  sahin
 */
public class frmNearestPOI extends javax.swing.JFrame {
    
      Main parent;
    public frmNearestPOI(Main pParent) {
            parent= pParent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel5 = new javax.swing.JLabel();
        cmbCat = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnCategorySearch2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblocation = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Nearest POI");
        setResizable(false);
        jLabel5.setText("Category");

        cmbCat.setMaximumRowCount(4);
        cmbCat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cmbCat.setMaximumSize(new java.awt.Dimension(100, 200));
        cmbCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCatMouseClicked(evt);
            }
        });
        cmbCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCatItemStateChanged(evt);
            }
        });
        cmbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCatActionPerformed(evt);
            }
        });

        jLabel6.setText("Point");

        btnCategorySearch2.setText("Search");
        btnCategorySearch2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCategorySearch2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategorySearch2MouseClicked(evt);
            }
        });

        jButton6.setText("Goto");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        lblResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblocation.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Location");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel6)
                            .add(jLabel5)
                            .add(jLabel7))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, cmbCat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblocation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, lblResult, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnCategorySearch2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(cmbCat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lblocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(lblResult, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .add(26, 26, 26)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCategorySearch2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 32, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCatMouseClicked
        
    }//GEN-LAST:event_cmbCatMouseClicked

    private void cmbCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCatItemStateChanged
        
    }//GEN-LAST:event_cmbCatItemStateChanged

    private void cmbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCatActionPerformed
        if (evt.getActionCommand().equals("comboBoxChanged")) {
            
        }
    }//GEN-LAST:event_cmbCatActionPerformed

    private void btnCategorySearch2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategorySearch2MouseClicked
        parent.client.send("near:" + cmbCat.getSelectedItem().toString() +":"+parent.mapFileObject.currentFileCoordinate.ToString() );   
    }//GEN-LAST:event_btnCategorySearch2MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
  double positionX=Double.parseDouble( StringEX.split(lblResult.getText(),' ')[0]);
  double positionY=Double.parseDouble(StringEX.split(lblResult.getText(),' ')[1]) ;
        parent.mapFileObject.setPosition(positionX,positionY);    
        this.setVisible(false);
    }//GEN-LAST:event_jButton6MouseClicked
    
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorySearch2;
    public javax.swing.JComboBox cmbCat;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel lblResult;
    public javax.swing.JLabel lblocation;
    // End of variables declaration//GEN-END:variables
    
}
