/*
 * frmRoutePointSelector.java
 *
 * Created on January 4, 2008, 12:32 AM
 */

package RouteSearch;

import GuideME.Main;
import Helper.PointF;
import javax.swing.JTextField;

/**
 *
 * @author  sahin
 */
public class frmRoutePointSelector extends javax.swing.JFrame {
    
    private JTextField  editingPoint;
    
    public void setEditingPoint(JTextField value){
        editingPoint=value;
    }
    
    public JTextField getEditingPoint(){
        return editingPoint;
    }
    Main parent;
    /** Creates new form frmRoutePointSelector */
    public frmRoutePointSelector(Main pParent) {
        this.parent=pParent;
        
        initComponents();
        //  jPanel3.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnClose = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cmbCategory = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnCategorySearch = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtStreet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnStreetSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        cmbStreet = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBounds(new java.awt.Rectangle(0, 0, 240, 240));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnClose.setText("X");
        btnClose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnClose.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnClose.setMaximumSize(new java.awt.Dimension(20, 19));
        btnClose.setMinimumSize(new java.awt.Dimension(20, 19));
        btnClose.setPreferredSize(new java.awt.Dimension(20, 19));
        btnClose.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnClose.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 20, -1));

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTabbedPane1VetoableChange(evt);
            }
        });

        cmbCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbCategoryMouseClicked(evt);
            }
        });
        cmbCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoryItemStateChanged(evt);
            }
        });
        cmbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoryActionPerformed(evt);
            }
        });

        jLabel1.setText("Category");

        btnCategorySearch.setText("Search");
        btnCategorySearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCategorySearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategorySearchMouseClicked(evt);
            }
        });

        jLabel3.setText("Name");

        txtCategory.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setText("Pick");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Connecting.."
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtCategory)
                    .add(cmbCategory, 0, 161, Short.MAX_VALUE))
                .add(15, 15, 15))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(btnCategorySearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(139, 139, 139))
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(cmbCategory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(txtCategory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnCategorySearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jTabbedPane1.addTab("Catagory", jPanel1);

        txtStreet.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Street");

        btnStreetSearch.setText("Search");
        btnStreetSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStreetSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStreetSearchMouseClicked(evt);
            }
        });

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Connecting..."
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        jButton5.setText("Pick");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        cmbStreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbStreetMouseClicked(evt);
            }
        });
        cmbStreet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbStreetItemStateChanged(evt);
            }
        });
        cmbStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStreetActionPerformed(evt);
            }
        });

        jLabel4.setText("Category");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnStreetSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(138, 138, 138))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jLabel2))
                            .add(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jLabel4)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtStreet)
                            .add(cmbStreet, 0, 163, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(cmbStreet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2)
                    .add(txtStreet, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .add(btnStreetSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jTabbedPane1.addTab("Street", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbCategoryMouseClicked
        
    }//GEN-LAST:event_cmbCategoryMouseClicked

    private void cmbCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoryItemStateChanged
        
    }//GEN-LAST:event_cmbCategoryItemStateChanged

    private void cmbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryActionPerformed
        if (evt.getActionCommand().equals("comboBoxChanged")) {
            parent.client.send("ss:Categories$POI$" + cmbCategory.getSelectedItem().toString() +":C");
        }
    }//GEN-LAST:event_cmbCategoryActionPerformed

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseMouseClicked
    
    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        
        
    }//GEN-LAST:event_jTabbedPane1StateChanged
    
    private void jTabbedPane1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_jTabbedPane1VetoableChange
        
    }//GEN-LAST:event_jTabbedPane1VetoableChange
    
    private void cmbStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStreetActionPerformed
        parent.client.send("ss:Categories$POLYLINE$" + cmbStreet.getSelectedItem().toString() +":S");
    }//GEN-LAST:event_cmbStreetActionPerformed
    
    private void cmbStreetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbStreetItemStateChanged
        
    }//GEN-LAST:event_cmbStreetItemStateChanged
    
    private void cmbStreetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbStreetMouseClicked
        
    }//GEN-LAST:event_cmbStreetMouseClicked
    
    private void btnStreetSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStreetSearchMouseClicked
        parent.client.send("ss:Categories$POLYLINE$" + cmbStreet.getSelectedItem().toString() +"$"+txtStreet.getText()+":S" );
        
        
    }//GEN-LAST:event_btnStreetSearchMouseClicked
    
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
    editingPoint.setText(jTable3.getValueAt(jTable3.getSelectedRow(),1).toString() );
        this.setVisible(false);
    }//GEN-LAST:event_jButton5MouseClicked
    
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        
        editingPoint.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString() );
        this.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked
        
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
//parent.objfrmRoutePointSelector.jPanel3.setVisible(true);
        parent.client.send("list:Categories$POLYLINE:S");
        parent.client.send("list:Categories$POI:C");
        
    }//GEN-LAST:event_formWindowActivated
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened
        
    private void btnCategorySearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategorySearchMouseClicked
        parent.client.send("ss:Categories$POI$" + cmbCategory.getSelectedItem().toString() +"$"+txtCategory.getText()+":C" );
    }//GEN-LAST:event_btnCategorySearchMouseClicked
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategorySearch;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnStreetSearch;
    public javax.swing.JComboBox cmbCategory;
    public javax.swing.JComboBox cmbStreet;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable3;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
    
}
