/*
 * frmResults.java
 *
 * Created on January 4, 2008, 1:14 AM
 */

package RouteSearch;

import GuideME.Main;
import GuideME.StringEX;

/**
 *
 * @author  sahin
 */
public class frmResults extends javax.swing.JFrame {
    static {
        try {
         //   javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch(Exception exception) {
            System.out.println("Error loading L&F: " + exception);
        }
    }
    Main parent;
    /** Creates new form frmResults */
    public frmResults(Main pParent) {
        parent=pParent;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnClose = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        btnClose.setText("X");
        btnClose.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 20, 20));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setPreferredSize(new java.awt.Dimension(240, 214));
        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sonuc Yok"
            }
        ));
        jScrollPane3.setViewportView(tblResult);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 240, 210));

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Search Result");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 20));

        jButton1.setText("Go");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
String value= tblResult.getValueAt(tblResult.getSelectedRow(),2).toString();


        double dx=  Double.parseDouble( StringEX.split( value, ',')[0]  );
        double dy=  Double.parseDouble( StringEX.split( value, ',')[1]  );
        
        parent.mapFileObject.setPosition(dx,dy)    ;
       parent.mapFileObject.draw();
       this.setVisible(false);
        //tblResult.getSelectedRow(),1).toString()
    }//GEN-LAST:event_jButton1MouseClicked
    
    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable tblResult;
    // End of variables declaration//GEN-END:variables
    
}
