/*
 * frmRouteSearch.java
 *
 * Created on January 3, 2008, 3:04 AM
 */

package RouteSearch;

import GuideME.Main;
import GuideME.mapFile;
import RouteSearch.frmRoutePointSelector;
import java.awt.Font;

/**
 *
 * @author  sahin
 */
public class frmRouteSearch extends javax.swing.JFrame {
    static {
        try {
 //           javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch(Exception exception) {
            System.out.println("Error loading L&F: " + exception);
        }
    }
    
    mapFile Map;
    Main parent;

  
    /** Creates new form frmRouteSearch */
    public frmRouteSearch(Main pParent) {
        initComponents();
        parent= pParent;
        Map=parent.mapFileObject;
        
        try{
                
            txtFrom.setText( String.valueOf(Map.startPoint.getX()).substring(0,8)+","+String.valueOf(Map.startPoint.getY()).substring(0,8) );
        }catch(Exception e){
            
        }
        try{        
            txtTo.setText( String.valueOf(Map.endPoint.getX()).substring(0,8)+","+String.valueOf(Map.endPoint.getY()).substring(0,8) );
            }catch(Exception e){
            
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblFrom = new javax.swing.JLabel();
        txtFrom = new javax.swing.JTextField();
        lblTo = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        btnFrom = new javax.swing.JButton();
        btnTo = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Route Search");
        setBounds(new java.awt.Rectangle(0, 0, 240, 240));
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });

        lblFrom.setText("From");

        txtFrom.setText("40.98952 29.03695");
        txtFrom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTo.setText("To");

        txtTo.setText("41.06088 28.96635");
        txtTo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnFrom.setText("...");
        btnFrom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnFrom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFromMouseClicked(evt);
            }
        });

        btnTo.setText("...");
        btnTo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnToMouseClicked(evt);
            }
        });

        btnFind.setText("Search");
        btnFind.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFindMouseClicked(evt);
            }
        });

        jLabel1.setText("Select destination and start point.");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel1))
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblFrom)
                    .add(lblTo))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtTo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .add(txtFrom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(btnTo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(btnFrom, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .add(btnFind, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(11, 11, 11)
                .add(jLabel1)
                .add(6, 6, 6)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(lblFrom)
                        .add(txtFrom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(btnFrom))
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(lblTo)
                            .add(txtTo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10))
                    .add(btnTo))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(btnFind, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindMouseClicked
parent.client.send("astar:"+txtFrom.getText().replace(' ',':')+":"+txtTo.getText().replace(' ',':') );
this.setVisible(false);
    }//GEN-LAST:event_btnFindMouseClicked
  
    
    private void btnToMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnToMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                parent.objfrmRoutePointSelector.setVisible(true);
                parent.objfrmRoutePointSelector.setEditingPoint(txtTo);
            }
        });
    }//GEN-LAST:event_btnToMouseClicked
    
    private void btnFromMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFromMouseClicked
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                parent.objfrmRoutePointSelector.setVisible(true);
                parent.objfrmRoutePointSelector.setEditingPoint(txtFrom);
            }
        });
    }//GEN-LAST:event_btnFromMouseClicked
    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
// TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged
    
    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFrom;
    private javax.swing.JButton btnTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblTo;
    public javax.swing.JTextField txtFrom;
    public javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
    
}
